name=DALI-ESP32
version=1.0.0
author=silahcen001
maintainer=silahcen001
sentence=DALI controller for ESP32.
paragraph=A hardware-driven DALI communication library utilizing the native ESP32 RMT peripheral.
category=Device Control
url=https://github.com/silahcen001/DALI-ESP32
architectures=esp32
includes=DaliController.h
license=GPL-3.0
